version: '3'

services:
  db:
    build:
      context: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: TrackErrors
      MYSQL_USER: TrackErrors
      MYSQL_PASSWORD: letmein12
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d/:ro
    - /var/www/verify/mysql:/var/lib/mysql
    ports:
    - '3307:3306'
    container_name: verify-mariadb
    restart: always


  app:
    build: .
    container_name: verify-app
    command: gunicorn verify.wsgi:application --bind 0.0.0.0:8000 --timeout=3600 --workers=10
    volumes:
    - .:/code
    - /var/www/verify/media:/verify-app/media
    - /var/www/verify/static:/verify-app/static
    ports:
    - '8001:8000'
    depends_on:
      - db
    environment:
      VERIFY_MYSQL_HOST: db
      VERIFY_MYSQL_DATABASE: TrackErrors
      VERIFY_MYSQL_USER: TrackErrors
      VERIFY_MYSQL_PASSWORD: letmein12
      VERIFY_MYSQL_PORT: 3306
    restart: always

  nginx:
    container_name: verify-nginx
    build: ./nginx
    ports:
    - 5004:80
    depends_on:
      - app
    volumes:
      - /var/www/verify/media:/files/media
      - /var/www/verify/static:/files/static
    restart: always