# Generated by Django 2.0.2 on 2018-02-09 06:14

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='field_unique',
            field=api.models.ListField(max_length=500, verbose_name='Unique Fields'),
        ),
    ]
