# Generated by Django 2.0.2 on 2018-04-13 06:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='mapping',
            field=api.models.DictField(help_text="Dict of mapping between  {'variable in error script':'variable in image database'}", max_length=500, verbose_name='Mapping'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='script',
            field=models.CharField(max_length=100, verbose_name='Location of Error script'),
        ),
    ]
