# Generated by Django 2.0.2 on 2018-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180413_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
