# Generated by Django 2.0.2 on 2018-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180209_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='record_id',
            field=models.CharField(max_length=100, verbose_name='Record id'),
        ),
    ]
