# Generated by Django 2.0.2 on 2018-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180209_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(help_text='Hospital Id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hospital name', max_length=250)),
            ],
        ),
    ]
