# Generated by Django 2.0.2 on 2018-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180418_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='note',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
