# Generated by Django 2.0.2 on 2018-03-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hosp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hospital'),
        ),
    ]
