# Generated by Django 2.0.2 on 2018-05-16 12:01

from django.db import migrations

def autofill_validation(apps,schema_editor):
    Image=apps.get_model('api',"Image")
    Validation=apps.get_model('api',"Validation")
    try:
        v=Validation.objects.get(validation_id='cin_peads')
        for im in Image.objects.all():
            im.validation=v
            im.save()

    except:
        pass
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_image_validation'),
    ]

    operations = [
        migrations.RunPython(autofill_validation)
    ]
