# Generated by Django 2.0.2 on 2019-05-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_Data_migrate_Images'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('validation', 'values')},
        ),
    ]
