# Generated by Django 2.0.2 on 2019-12-19 05:32

import api2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', api2.models.DictField(help_text='Unique identifier', max_length=1000)),
                ('checked', models.BooleanField(default=False, help_text='Verified?')),
                ('note', models.TextField(default='', max_length=1000)),
                ('date_created', models.DateField(auto_now=True, help_text='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.IntegerField(help_text='Hospital Id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hospital name', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100, verbose_name='Record id')),
                ('ipno', models.CharField(max_length=250, verbose_name='iP Number')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to=api2.models.get_upload_filename, verbose_name='image file')),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.Hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('record_id', models.CharField(max_length=100, verbose_name='record id')),
                ('variable', models.CharField(max_length=100, verbose_name='Variable')),
                ('value', models.CharField(max_length=500, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_id', models.CharField(max_length=30, unique=True, verbose_name='Validation id')),
                ('name', models.CharField(max_length=100, verbose_name='Name of validation')),
                ('field_unique', api2.models.ListField(max_length=500, verbose_name='Unique Fields')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last updated')),
                ('script', models.CharField(max_length=100, verbose_name='Location of Error script')),
                ('mapping', api2.models.DictField(help_text="Dict of mapping between  {'variable in error script':'variable in image database'}", max_length=500, verbose_name='Mapping')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api2.Validation'),
        ),
        migrations.AddField(
            model_name='history',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.Validation'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('validation', 'values')},
        ),
    ]
